### ISSUE TITLE
Crate only works with rlua version 0.17

### ISSUE THREAD

**Issue by rymdbar** [yancouto/rlua-builders#2]
When attempting to build a trivial project based on coping and pasting the example from the documentation, `cargo check` fails with:

```
    Checking rlua-build v0.1.0 (/rlua-build)
error[E0277]: the trait bound `Person: rlua::userdata::UserData` is not satisfied
  --> src/main.rs:3:10
   |
3  | #[derive(LuaBuilder, UserData, Clone, PartialEq, Debug)]
   |          ^^^^^^^^^^ the trait `rlua::userdata::UserData` is not implemented for `Person`
   |
note: required by a bound in `LuaBuilder`
  --> /rlua-build/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-builders-0.1.4/src/lib.rs:95:41
   |
95 | pub trait LuaBuilder<'s, T: ToLua<'s>>: UserData + Clone {
   |                                         ^^^^^^^^ required by this bound in `LuaBuilder`
   = note: this error originates in the derive macro `LuaBuilder` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `LuaFunction<'s>: rlua::userdata::UserData` is not satisfied
  --> src/main.rs:3:10
   |
3  | #[derive(LuaBuilder, UserData, Clone, PartialEq, Debug)]
   |          ^^^^^^^^^^ the trait `rlua::userdata::UserData` is not implemented for `LuaFunction<'s>`
   |
   = note: required because of the requirements on the impl of `rlua::value::ToLua<'s>` for `LuaFunction<'s>`
note: required by a bound in `LuaBuilder`
  --> /rlua-build/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-builders-0.1.4/src/lib.rs:95:29
   |
95 | pub trait LuaBuilder<'s, T: ToLua<'s>>: UserData + Clone {
   |                             ^^^^^^^^^ required by this bound in `LuaBuilder`
   = note: this error originates in the derive macro `LuaBuilder` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `*mut rlua_lua54_sys::bindings::lua_State` cannot be sent between threads safely
  --> src/main.rs:3:10
   |
3  | #[derive(LuaBuilder, UserData, Clone, PartialEq, Debug)]
   |          ^^^^^^^^^^ `*mut rlua_lua54_sys::bindings::lua_State` cannot be sent between threads safely
   |
   = help: within `LuaFunction<'s>`, the trait `Send` is not implemented for `*mut rlua_lua54_sys::bindings::lua_State`
   = note: required because it appears within the type `LuaContext<'s>`
   = note: required because it appears within the type `rlua::types::LuaRef<'s>`
   = note: required because it appears within the type `LuaFunction<'s>`
   = note: required because of the requirements on the impl of `rlua::value::ToLua<'s>` for `LuaFunction<'s>`
note: required by a bound in `LuaBuilder`
  --> /rlua-build/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-builders-0.1.4/src/lib.rs:95:29
   |
95 | pub trait LuaBuilder<'s, T: ToLua<'s>>: UserData + Clone {
   |                             ^^^^^^^^^ required by this bound in `LuaBuilder`
   = note: this error originates in the derive macro `LuaBuilder` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: `*mut PhantomData<UnsafeCell<()>>` cannot be sent between threads safely
  --> src/main.rs:3:10
   |
3  | #[derive(LuaBuilder, UserData, Clone, PartialEq, Debug)]
   |          ^^^^^^^^^^ `*mut PhantomData<UnsafeCell<()>>` cannot be sent between threads safely
   |
   = help: within `LuaFunction<'s>`, the trait `Send` is not implemented for `*mut PhantomData<UnsafeCell<()>>`
   = note: required because it appears within the type `PhantomData<*mut PhantomData<UnsafeCell<()>>>`
   = note: required because it appears within the type `LuaContext<'s>`
   = note: required because it appears within the type `rlua::types::LuaRef<'s>`
   = note: required because it appears within the type `LuaFunction<'s>`
   = note: required because of the requirements on the impl of `rlua::value::ToLua<'s>` for `LuaFunction<'s>`
note: required by a bound in `LuaBuilder`
  --> /rlua-build/.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-builders-0.1.4/src/lib.rs:95:29
   |
95 | pub trait LuaBuilder<'s, T: ToLua<'s>>: UserData + Clone {
   |                             ^^^^^^^^^ required by this bound in `LuaBuilder`
   = note: this error originates in the derive macro `LuaBuilder` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `rlua-build` due to 4 previous errors
```

Using rlua 0.17.0 or 0.17.1 seems to make the build succeed. Newer, as well as older, rlua versions fail. I have not made any attempts at understanding the cause of the error.

**Comment by yancouto** [comment]
That's the issue with pre-1.0 versions, any bump might be backwards incompatible according to [semver](https://semver.org/#spec-item-4).

I use dependency `rlua = "0.17"` in the `Cargo.toml`, which I would expect cargo to complain if you try with a later version according [to this wiki](https://doc.rust-lang.org/cargo/reference/semver.html#change-categories).

Feel free to submit a PR to lock the version to rlua 0.17, or to update to a newer rlua version. I'm not actively working on this project anymore, but can review.

**Comment by BenMcAvoy** [comment]
Are there any plans on fixing this? (As in, any plans to update `rlua-builders`)

**Comment by rymdbar** [comment]
@BenMcAvoy Yes, that task has been assigned to you!

Seriously; The maintainer has replied with a very clear answer about him not actively working on this project, **and** instructed what the constructive path forward would be for anyone wishing to actually make a contribution.

Since leaving this issue (and github tickets in general) open apparently attracts unproductive negative-value comments, I'm closing it. I realize that this unfortunately might make information harder to find for those who come here in the future to evaluate the state of the crate. If anyone wishes to reopen the ticket, please keep me out of the loop.
